version: "3.9"

services:
  frontend:
    # stdin_open: true # get you inside the container
    build: .
    ports:
      - "3000:3000"
    volumes:
      # - "app/node_modules" # in case you need to debug some node_modules
      - "./:/app" # HOT Reload enabled
